//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ch.rc
//
#define RT_TEXT                         25
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SYSTEMTYPE                  129
#define IDR_POPUP_MENU                  130
#define IDD_STATUS_DIALOG               131
#define IDR_PRIORITY_MENU               135
#define IDR_BUFFERSIZE_MENU             136
#define IDD_BUFFERSIZE_DIALOG           137
#define IDR_PAUSE_LIST_MENU             138
#define IDI_ERROR_ICON                  139
#define IDI_WORKING_ICON                140
#define IDI_PAUSED_ICON                 141
#define IDI_FINISHED_ICON               142
#define IDI_CANCELLED_ICON              143
#define IDD_OPTIONS_DIALOG              144
#define IDD_MINIVIEW_DIALOG             145
#define IDI_WAITING_ICON                146
#define IDD_CUSTOM_COPY_DIALOG          149
#define IDD_FOLDER_BROWSING_DIALOG      150
#define IDD_NEW_FOLDER_DIALOG           151
#define IDD_NEW_QUICK_ACCESS_DIALOG     152
#define IDR_ADVANCED_MENU               160
#define IDD_REPLACE_PATHS_DIALOG        161
#define IDI_QUESTION_ICON               163
#define IDD_FEEDBACK_DSTFILE_DIALOG     167
#define IDD_FEEDBACK_FILE_ERROR_DIALOG  167
#define IDD_FEEDBACK_NOTENOUGHSPACE_DIALOG 173
#define IDI_INFO_ICON                   175
#define IDI_ERR_ICON                    176
#define IDI_WARNING_ICON                177
#define IDD_SHUTDOWN_DIALOG             182
#define IDI_SHUTDOWN_ICON               185
#define IDI_NET_ICON                    186
#define IDI_HDD_ICON                    188
#define IDI_CD_ICON                     189
#define IDI_HDD2_ICON                   190
#define IDI_TRIBE_ICON                  191
#define IDI_FOLDER_ICON                 192
#define IDD_FILTER_DIALOG               195
#define IDI_ADDSHORTCUT_ICON            198
#define IDI_DELETESHORTCUT_ICON         199
#define IDI_LARGEICONS_ICON             200
#define IDI_LIST_ICON                   201
#define IDI_NEWFOLDER_ICON              202
#define IDI_REPORT_ICON                 203
#define IDI_SMALLICONS_ICON             204
#define IDD_SHORTCUTEDIT_DIALOG         208
#define IDD_RECENTEDIT_DIALOG           209
#define IDC_ABOUTBOX                    210
#define IDD_CRASH_DIALOG                212
#define IDD_UPDATER_DIALOG              213
#define IDD_FEEDBACK_REPLACE_DIALOG     214
#define IDC_PROGRAM_STATIC              1000
#define IDC_ADDFILE_BUTTON              1002
#define IDC_STATUS_LIST                 1003
#define IDC_REMOVEFILEFOLDER_BUTTON     1004
#define IDC_ALL_PROGRESS                1005
#define IDC_DESTPATH_EDIT               1006
#define IDC_TASK_PROGRESS               1007
#define IDC_DESTBROWSE_BUTTON           1008
#define IDC_OPERATION_COMBO             1009
#define IDC_FILTERS_LIST                1010
#define IDC_ADDDIR_BUTTON               1011
#define IDC_BUFFERSIZES_LIST            1012
#define IDC_SET_BUFFERSIZE_BUTTON       1013
#define IDC_FILTERS_CHECK               1014
#define IDC_IGNOREFOLDERS_CHECK         1015
#define IDC_SET_PRIORITY_BUTTON         1016
#define IDC_ONLYSTRUCTURE_CHECK         1017
#define IDC_PAUSE_BUTTON                1018
#define IDC_STANDARD_CHECK              1019
#define IDC_FORCEDIRECTORIES_CHECK      1020
#define IDC_RESUME_BUTTON               1021
#define IDC_CANCEL_BUTTON               1022
#define IDC_ADVANCED_CHECK              1023
#define IDC_BUFFERSIZES_BUTTON          1024
#define IDC_ADDFILTER_BUTTON            1025
#define IDC_REMOVEFILTER_BUTTON         1026
#define IDC_SOURCE_STATIC               1027
#define IDC_DESTINATION_STATIC          1028
#define IDC_OPERATION_STATIC            1029
#define IDC_BUFFERSIZE_STATIC           1030
#define IDC_PRIORITY_STATIC             1031
#define IDC_ERRORS_STATIC               1032
#define IDC_PROGRESS_STATIC             1033
#define IDC_TRANSFER_STATIC             1034
#define IDC_OVERALL_PROGRESS_STATIC     1035
#define IDC_OVERALL_TRANSFER_STATIC     1036
#define IDC_TIME_STATIC                 1037
#define IDC_ROLL_UNROLL_BUTTON          1038
#define IDC_SIZE_EDIT                   1039
#define IDC_ASSOCIATEDFILES__STATIC     1040
#define IDC_START_ALL_BUTTON            1041
#define IDC_RESTART_BUTTON              1042
#define IDC_DELETE_BUTTON               1043
#define IDC_PAUSE_ALL_BUTTON            1044
#define IDC_RESTART_ALL_BUTTON          1045
#define IDC_CANCEL_ALL_BUTTON           1046
#define IDC_REMOVE_FINISHED_BUTTON      1047
#define IDC_PROPERTIES_LIST             1048
#define IDC_PROGRESS_LIST               1049
#define IDC_SOURCE_EDIT                 1050
#define IDC_DESTINATION_EDIT            1051
#define IDC_DIRECTORY_TREE              1053
#define IDC_QUICK_ACCESS_LIST           1054
#define IDC_PATH_EDIT                   1055
#define IDC_HEADER_TEXT_STATIC          1056
#define IDC_FIND_PATH_BUTTON            1057
#define IDC_NEW_FOLDER_BUTTON           1058
#define IDC_PATH_STATIC                 1059
#define IDC_ADD_BUTTON                  1060
#define IDC_REMOVE_BUTTON               1061
#define IDC_TITLE_EDIT                  1062
#define IDC_BROWSE_BUTTON               1064
#define IDC_FILES_LIST                  1065
#define IDC_ADD_DIRECTORY_BUTTON        1066
#define IDC_MASK_EDIT                   1067
#define IDC_OPERATION_TYPE_COMBO        1068
#define IDC_ADD_FILES_BUTTON            1069
#define IDC_BUFFERSIZE_EDIT             1070
#define IDC_PRIORITY_COMBO              1071
#define IDC_IGNORE_FOLDERS_CHECK        1073
#define IDC_ONLY_CREATE_CHECK           1074
#define IDC_ADVANCED_BUTTON             1077
#define IDC_PATHS_LIST                  1078
#define IDC_DESTFILENAME_EDIT           1090
#define IDC_IGNORE_BUTTON               1097
#define IDC_RETRY_BUTTON                1100
#define IDC_COPY_REST_BUTTON            1103
#define IDC_COUNT_EDIT                  1119
#define IDC_SHOW_LOG_BUTTON             1120
#define IDC_STICK_BUTTON                1122
#define IDC_FREESPACE_STATIC            1123
#define IDC_DISK_STATIC                 1124
#define IDC_REQUIRED_STATIC             1127
#define IDC_AVAILABLE_STATIC            1128
#define IDC_TEST_BUTTON                 1129
#define IDC_SOURCEFILENAME_EDIT         1130
#define IDC_YESALL_BUTTON               1131
#define IDC_NOALL_BUTTON                1132
#define IDC_DEFAULTMULTIPLIER_COMBO     1133
#define IDC_DEFAULTSIZE_EDIT            1134
#define IDC_ONEDISKSIZE_EDIT            1135
#define IDC_CHANGEBUFFER_BUTTON         1137
#define IDC_ONEDISKMULTIPLIER_COMBO     1138
#define IDC_TWODISKSSIZE_EDIT           1139
#define IDC_TWODISKSMULTIPLIER_COMBO    1140
#define IDC_CDROMSIZE_EDIT              1141
#define IDC_CDROMMULTIPLIER_COMBO       1142
#define IDC_LANSIZE_EDIT                1143
#define IDC_LANMULTIPLIER_COMBO         1144
#define IDC_ONLYDEFAULT_CHECK           1145
#define IDC_TIME_PROGRESS               1146
#define IDC_ERRORS_EDIT                 1147
#define IDC_FILTER_COMBO                1149
#define IDC_FILTER_CHECK                1150
#define IDC_SIZE_CHECK                  1151
#define IDC_SIZE1_EDIT                  1152
#define IDC_SIZE1MULTI_COMBO            1153
#define IDC_SIZETYPE1_COMBO             1154
#define IDC_SIZE1_SPIN                  1155
#define IDC_SIZE2_EDIT                  1156
#define IDC_SIZE2MULTI_COMBO            1157
#define IDC_SIZETYPE2_COMBO             1158
#define IDC_SIZE2_SPIN                  1159
#define IDC_SIZE2_CHECK                 1160
#define IDC_DATE_CHECK                  1161
#define IDC_ATTRIBUTES_CHECK            1162
#define IDC_ARCHIVE_CHECK               1163
#define IDC_READONLY_CHECK              1164
#define IDC_HIDDEN_CHECK                1165
#define IDC_SYSTEM_CHECK                1166
#define IDC_DATETYPE_COMBO              1167
#define IDC_DATE1TYPE_COMBO             1168
#define IDC_DATE1_DATETIMEPICKER        1169
#define IDC_TIME1_DATETIMEPICKER        1170
#define IDC_DATE2_CHECK                 1171
#define IDC_DATE2TYPE_COMBO             1172
#define IDC_DATE2_DATETIMEPICKER        1173
#define IDC_TIME2_DATETIMEPICKER        1174
#define IDC_DIRECTORY_CHECK             1175
#define IDC_FILTEREXCLUDE_COMBO         1176
#define IDC_EXCLUDEMASK_CHECK           1177
#define IDC_COUNT_SPIN                  1178
#define IDC_DESTPATH_COMBOBOXEX         1179
#define IDC_SHORTCUT_LIST               1180
#define IDC_NAME_EDIT                   1181
#define IDC_PATH_COMBOBOXEX             1182
#define IDC_CHANGE_BUTTON               1185
#define IDC_RECENT_LIST                 1190
#define IDC_IMPORT_BUTTON               1191
#define IDC_UP_BUTTON                   1192
#define IDC_DOWN_BUTTON                 1193
#define IDC_THANX_EDIT                  1198
#define IDC_COPYRIGHT_STATIC            1199
#define IDC_FOLDER_TREE                 1200
#define IDC_DISTRIBUTION_STATIC         1200
#define IDC_NEWFOLDER_BUTTON            1201
#define IDC_HOMEPAGE_STATIC             1201
#define IDC_TITLE_STATIC                1202
#define IDC_HOMEPAGELINK_STATIC         1202
#define IDC_LARGEICONS_BUTTON           1203
#define IDC_CONTACT_STATIC              1203
#define IDC_HOMEPAGELINK2_STATIC        1203
#define IDC_SMALLICONS_BUTTON           1204
#define IDC_GENFORUM_STATIC             1204
#define IDC_LIST_BUTTON                 1205
#define IDC_DEVFORUM_STATIC             1205
#define IDC_REPORT_BUTTON               1206
#define IDC_CONTACT1LINK_STATIC         1206
#define IDC_CONTACT2LINK_STATIC         1207
#define IDC_GENFORUMPAGELINK_STATIC     1208
#define IDC_TOGGLE_BUTTON               1209
#define IDC_GENFORUMSUBSCRIBELINK_STATIC 1209
#define IDC_ADDSHORTCUT_BUTTON          1210
#define IDC_GENFORUMUNSUBSCRIBELINK_STATIC 1210
#define IDC_REMOVESHORTCUT_BUTTON       1211
#define IDC_GENFORUMSENDLINK_STATIC     1211
#define IDC_DEVFORUMPAGELINK_STATIC     1212
#define IDC_DEVFORUMSUBSCRIBELINK_STATIC 1213
#define IDC_DEVFORUMUNSUBSCRIBELINK_STATIC 1214
#define IDC_DEVFORUMSENDLINK_STATIC     1215
#define IDC_THANX_STATIC                1216
#define IDC_UPX_STATIC                  1217
#define IDC_CONTACT3LINK_STATIC         1217
#define IDC_APPLY_BUTTON                1218
#define IDC_001_STATIC                  1219
#define IDC_002_STATIC                  1220
#define IDC_003_STATIC                  1221
#define IDC_004_STATIC                  1222
#define IDC_005_STATIC                  1223
#define IDC_006_STATIC                  1224
#define IDC_007_STATIC                  1225
#define IDC_008_STATIC                  1226
#define IDC_009_STATIC                  1227
#define IDC_010_STATIC                  1228
#define IDC_011_STATIC                  1229
#define IDC_012_STATIC                  1230
#define IDC_013_STATIC                  1231
#define IDC_014_STATIC                  1232
#define IDC_015_STATIC                  1233
#define IDC_016_STATIC                  1234
#define IDC_017_STATIC                  1235
#define IDC_018_STATIC                  1236
#define IDC_019_STATIC                  1237
#define IDC_020_STATIC                  1238
#define IDC_021_STATIC                  1239
#define IDC_022_STATIC                  1240
#define IDC_023_STATIC                  1241
#define IDC_024_STATIC                  1242
#define IDC_025_STATIC                  1243
#define IDC_026_STATIC                  1244
#define IDC_027_STATIC                  1245
#define IDC_028_STATIC                  1246
#define IDC_029_STATIC                  1247
#define IDC_030_STATIC                  1248
#define IDC_BAR1_STATIC                 1249
#define IDC_BAR2_STATIC                 1250
#define IDC_BAR3_STATIC                 1251
#define IDC_BAR4_STATIC                 1252
#define IDC_BAR5_STATIC                 1253
#define IDC_HEADER_STATIC               1254
#define IDC_HOSTLINK_STATIC             1255
#define IDC_HELP_BUTTON                 1257
#define IDC_PROGRAM_STATICEX            1263
#define IDC_FULLVERSION_STATICEX        1264
#define IDC_HOMEPAGE_STATICEX           1265
#define IDC_CONTACT_STATICEX            1266
#define IDC_LICENSE_STATICEX            1267
#define IDC_CONTACTAUTHOR_STATICEX      1268
#define IDC_CONTACTSUPPORT_STATICEX     1269
#define IDC_SEND_CRASHDUMP_BUTTON       1272
#define IDC_STATIC00                    1275
#define IDC_STATIC_INFO                 1275
#define IDC_VERSION_STATIC              1276
#define IDC_VERSIONINFO_STATIC          1278
#define IDC_LOCATIONINFO_STATIC         1279
#define IDC_LOCATION_EDIT               1280
#define IDC_INFO_STATIC                 1282
#define IDC_OPEN_WEBPAGE_BUTTON         1283
#define IDC_LANGUAGE_STATIC             1284
#define IDC_REPLACE_BUTTON              1285
#define IDC_ALL_ITEMS_CHECK             1287
#define IDC_SKIP_BUTTON                 1288
#define IDC_SRC_ICON_STATIC             1291
#define IDC_DST_ICON_STATIC             1292
#define IDC_SRC_INFO_STATIC             1293
#define IDC_DST_INFO_STATIC             1294
#define IDC_DESC_STATIC                 1297
#define IDC_00_STATIC                   1298
#define IDC_01_STATIC                   1299
#define IDS_APPNAME_STRING              5000
#define IDS_PRIORITY0_STRING            5001
#define IDS_PRIORITY1_STRING            5002
#define IDS_PRIORITY2_STRING            5003
#define IDS_PRIORITY3_STRING            5004
#define IDS_PRIORITY4_STRING            5005
#define IDS_PRIORITY5_STRING            5006
#define IDS_PRIORITY6_STRING            5007
#define IDS_FIRSTCOPY_STRING            5008
#define IDS_NEXTCOPY_STRING             5009
#define IDS_NOTFOUND_STRING             5010
#define IDS_BYTE_STRING                 5011
#define IDS_KBYTE_STRING                5012
#define IDS_MBYTE_STRING                5013
#define IDS_GBYTE_STRING                5014
#define IDS_TBYTE_STRING                5015
#define IDS_PBYTE_STRING                5016
#define IDS_LT_STRING                   5017
#define IDS_LE_STRING                   5018
#define IDS_EQ_STRING                   5019
#define IDS_GE_STRING                   5020
#define IDS_GT_STRING                   5021
#define IDS_UPDATER_NEW_VERSION_STRING  5022
#define IDS_UPDATER_OLD_VERSION_STRING  5023
#define IDS_UPDATER_EQUAL_VERSION_STRING 5024
#define IDS_UPDATER_ERROR_STRING        5025
#define IDS_UPDATER_WAITING_STRING      5026
#define IDS_SHELL_EXTENSION_MISMATCH_STRING 5027
#define IDS_ONECOPY_STRING              6000
#define IDS_REGISTEROK_STRING           6001
#define IDS_REGISTERERR_STRING          6002
#define IDS_UNREGISTEROK_STRING         6003
#define IDS_UNREGISTERERR_STRING        6004
#define IDS_CRASH_STRING                6006
#define IDS_PROGRAM_STRING              8000
#define IDS_CLIPBOARDMONITORING_STRING  8001
#define IDS_CLIPBOARDINTERVAL_STRING    8002
#define IDS_AUTORUNPROGRAM_STRING       8003
#define IDS_AUTOSHUTDOWN_STRING         8004
#define IDS_AUTOSAVEINTERVAL_STRING     8005
#define IDS_TEMPFOLDER_STRING           8006
#define IDS_STATUSWINDOW_STRING         8007
#define IDS_REFRESHSTATUSINTERVAL_STRING 8008
#define IDS_STATUSSHOWDETAILS_STRING    8009
#define IDS_STATUSAUTOREMOVE_STRING     8010
#define IDS_MINIVIEW_STRING             8011
#define IDS_SHOWFILENAMES_STRING        8012
#define IDS_SHOWSINGLETASKS_STRING      8013
#define IDS_MINIVIEWREFRESHINTERVAL_STRING 8014
#define IDS_MINIVIEWSHOWAFTERSTART_STRING 8015
#define IDS_MINIVIEWAUTOHIDE_STRING     8016
#define IDS_PROCESSINGTHREAD_STRING     8017
#define IDS_AUTOCOPYREST_STRING         8018
#define IDS_SETDESTATTRIB_STRING        8019
#define IDS_SETDESTTIME_STRING          8020
#define IDS_PROTECTROFILES_STRING       8021
#define IDS_LIMITOPERATIONS_STRING      8022
#define IDS_SHOWVISUALFEEDBACK_STRING   8023
#define IDS_USETIMEDDIALOGS_STRING      8024
#define IDS_TIMEDDIALOGINTERVAL_STRING  8025
#define IDS_AUTORETRYONERROR_STRING     8026
#define IDS_AUTORETRYINTERVAL_STRING    8027
#define IDS_DEFAULTPRIORITY_STRING      8028
#define IDS_AUTODETECTBUFFERSIZE_STRING 8029
#define IDS_DEFAULTBUFFERSIZE_STRING    8030
#define IDS_DELETEAFTERFINISHED_STRING  8031
#define IDS_CREATELOGFILES_STRING       8032
#define IDS_SOUNDS_STRING               8033
#define IDS_PLAYSOUNDS_STRING           8034
#define IDS_SOUNDONERROR_STRING         8035
#define IDS_SOUNDONFINISH_STRING        8036
#define IDS_LANGUAGE_STRING             8037
#define IDS_READSIZEBEFOREBLOCK_STRING  8038
#define IDS_USENOBUFFERING_STRING       8039
#define IDS_LARGEFILESMINSIZE_STRING    8040
#define IDS_OPTIONSBUFFER_STRING        8041
#define IDS_ONEDISKBUFFERSIZE_STRING    8042
#define IDS_TWODISKSBUFFERSIZE_STRING   8043
#define IDS_CDBUFFERSIZE_STRING         8044
#define IDS_LANBUFFERSIZE_STRING        8045
#define IDS_SHUTDOWNTIME_STRING         8046
#define IDS_FORCESHUTDOWN_STRING        8047
#define IDS_MINIVIEWSMOOTHPROGRESS_STRING 8048
#define IDS_CFGFOLDERDIALOG_STRING      8049
#define IDS_CFGFDEXTVIEW_STRING         8050
#define IDS_CFGFDWIDTH_STRING           8051
#define IDS_CFGFDHEIGHT_STRING          8052
#define IDS_CFGFDSHORTCUTS_STRING       8053
#define IDS_CFGFDIGNOREDIALOGS_STRING   8054
#define IDS_CFGSHCOPY_STRING            8055
#define IDS_CFGSHMOVE_STRING            8056
#define IDS_CFGSHCMSPECIAL_STRING       8057
#define IDS_CFGSHPASTE_STRING           8058
#define IDS_CFGSHPASTESPECIAL_STRING    8059
#define IDS_CFGSHCOPYTO_STRING          8060
#define IDS_CFGSHMOVETO_STRING          8061
#define IDS_CFGSHCMTOSPECIAL_STRING     8062
#define IDS_CFGSHSHOWFREESPACE_STRING   8063
#define IDS_CFGSHSHOWICONS_STRING       8064
#define IDS_CFGSHINTERCEPTDRAG_STRING    8065
#define IDS_CFGSHORTCUTS_STRING         8066
#define IDS_CFGRECENT_STRING            8067
#define IDS_CFGSHELL_STRING             8068
#define IDS_CFGSCCOUNT_STRING           8069
#define IDS_CFGRPCOUNT_STRING           8070
#define IDS_CFGINTERCEPTKEYACTION_STRING 8071
#define IDS_CFGPRIORITYCLASS_STRING     8072
#define IDS_CFGDISABLEPRIORITYBOOST_STRING 8073
#define IDS_BOOLTEXT_STRING             8074
#define IDS_TEMPFOLDERCHOOSE_STRING     8075
#define IDS_FEEDBACKTYPE_STRING         8076
#define IDS_SOUNDSWAVFILTER_STRING      8077
#define IDS_LANGUAGELIST_STRING         8078
#define IDS_FORCESHUTDOWNVALUES_STRING  8079
#define IDS_CFGFDSHORTCUTSSTYLES_STRING 8080
#define IDS_CFGPRIORITYCLASSITEMS_STRING 8081
#define IDS_PLUGSFOLDER_STRING          8083
#define IDS_PLUGSFOLDERCHOOSE_STRING    8084
#define IDS_CFGLOGFILE_STRING           8085
#define IDS_CFGENABLELOGGING_STRING     8086
#define IDS_CFGMAXLIMIT_STRING          8088
#define IDS_CFGHELPDIR_STRING           8091
#define IDS_CFGHELPDIRCHOOSE_STRING     8092
#define IDS_LANGUAGESFOLDER_STRING      8093
#define IDS_LANGSFOLDERCHOOSE_STRING    8094
#define IDS_ABOUT_LANGUAGE_STRING       8095
#define IDS_CFGINTERCEPTCONTEXTMENU_STRING 8096
#define IDS_CFG_CHECK_FOR_UPDATES_FREQUENCY 8097
#define IDS_CFG_UPDATE_CHECK_FOR_BETA 8098
#define IDS_CFGLOGLEVEL				  8099
#define IDS_CFGLOGLEVEL_VALUES		  8100
#define IDS_UPDATE_FREQUENCIES			8101
#define IDS_MENUCOPY_STRING             9000
#define IDS_MENUMOVE_STRING             9001
#define IDS_MENUCOPYMOVESPECIAL_STRING  9002
#define IDS_MENUPASTE_STRING            9003
#define IDS_MENUPASTESPECIAL_STRING     9004
#define IDS_MENUCOPYTO_STRING           9005
#define IDS_MENUMOVETO_STRING           9006
#define IDS_MENUCOPYMOVETOSPECIAL_STRING 9007
#define IDS_MENUTIPCOPY_STRING          9008
#define IDS_MENUTIPMOVE_STRING          9009
#define IDS_MENUTIPCOPYMOVESPECIAL_STRING 9010
#define IDS_MENUTIPPASTE_STRING         9011
#define IDS_MENUTIPPASTESPECIAL_STRING  9012
#define IDS_MENUTIPCOPYTO_STRING        9013
#define IDS_MENUTIPMOVETO_STRING        9014
#define IDS_MENUTIPCOPYMOVETOSPECIAL_STRING 9015
#define IDS_BROWSE_STRING               13000
#define IDS_BDREMOTENAME_STRING         13001
#define IDS_BDLOCALNAME_STRING          13002
#define IDS_BDTYPE_STRING               13003
#define IDS_BDNETTYPE_STRING            13004
#define IDS_BDDESCRIPTION_STRING        13005
#define IDS_BDFREESPACE_STRING          13006
#define IDS_BDCAPACITY_STRING           13007
#define IDS_BDOK_STRING                 13008
#define IDS_BDCANCEL_STRING             13009
#define IDS_BDCANNOTCREATEFOLDER_STRING 13010
#define IDS_BDPATHDOESNTEXIST_STRING    13011
#define IDS_BDNAME_STRING               13012
#define IDS_BDPATH_STRING               13013
#define IDS_BDPATH2_STRING              13014
#define IDS_BDRIGHT_STRING              13015
#define IDS_BDLEFT_STRING               13016
#define IDS_BDNOSHORTCUTPATH_STRING     13017
#define IDS_BDNEWFOLDER_STRING          13018
#define IDS_BDLARGEICONS_STRING         13019
#define IDS_BDSMALLICONS_STRING         13020
#define IDS_BDLIST_STRING               13021
#define IDS_BDREPORT_STRING             13022
#define IDS_BDDETAILS_STRING            13023
#define IDS_BDADDSHORTCUT_STRING        13024
#define IDS_BDREMOVESHORTCUT_STRING     13025
#define IDS_BDDOMAIN_STRING             13026
#define IDS_BDSERVER_STRING             13027
#define IDS_BDSHARE_STRING              13028
#define IDS_BDFILE_STRING               13029
#define IDS_BDGROUP_STRING              13030
#define IDS_BDNETWORK_STRING            13031
#define IDS_BDROOT_STRING               13032
#define IDS_BDADMINSHARE_STRING         13033
#define IDS_BDDIR_STRING                13034
#define IDS_BDTREE_STRING               13035
#define IDS_BDNDSCONTAINER_STRING       13036
#define IDS_INFO_FILE_STRING            13037
#define IDS_INFO_SIZE_STRING            13038
#define IDS_INFO_MODIFIED_STRING        13039
#define IDS_INFO_REASON_STRING          13040
#define IDS_TITLECOPY_STRING            13500
#define IDS_TITLEMOVE_STRING            13501
#define IDS_TITLEUNKNOWNOPERATION_STRING 13502
#define IDS_MAINBROWSETEXT_STRING       13503
#define IDS_INFO_TWO_FILE_STRING		13504
#define IDS_ABTNOTHANX_STRING           14000
#define IDS_ABOUTVERSION_STRING         14001
#define IDS_BUFFERSIZEZERO_STRING       14500
#define IDS_FILEDLGALLFILTER_STRING     15000
#define IDS_DSTFOLDERBROWSE_STRING      15001
#define IDS_MISSINGDATA_STRING          15002
#define IDS_CCDCOPY_STRING              15003
#define IDS_CCDMOVE_STRING              15004
#define IDS_BSEDEFAULT_STRING           15005
#define IDS_BSEONEDISK_STRING           15006
#define IDS_BSETWODISKS_STRING          15007
#define IDS_BSECD_STRING                15008
#define IDS_BSELAN_STRING               15009
#define IDS_HDRMASK_STRING              15010
#define IDS_HDRSIZE_STRING              15011
#define IDS_HDRDATE_STRING              15012
#define IDS_HDRATTRIB_STRING            15013
#define IDS_AND_STRING                  15014
#define IDS_FILTERMASKEMPTY_STRING      15015
#define IDS_FILTERSIZE_STRING           15016
#define IDS_FILTERDATE_STRING           15017
#define IDS_HDREXCLUDEMASK_STRING       15018
#define IDS_HDREXCLUDEATTRIB_STRING     15019
#define IDS_FILTERATTRIB_STRING         15020
#define IDS_EMPTYFILTER_STRING          15021
#define IDS_FLTALLFILTER_STRING         15022
#define IDS_IMPORTREPORT_STRING         15023
#define IDS_IMPORTERROR_STRING          15024
#define IDS_NERPATH_STRING              16500
#define IDS_DATECREATED_STRING          18000
#define IDS_DATELASTWRITE_STRING        18001
#define IDS_DATEACCESSED_STRING         18002
#define IDS_MINIVIEWALL_STRING          18500
#define IDS_SOURCESTRINGMISSING_STRING  20000
#define IDS_SHORTCUTNAME_STRING         20500
#define IDS_SHORTCUTPATH_STRING         20501
#define IDS_SHUTDOWNERROR_STRING        21000
#define IDS_COLUMNSTATUS_STRING         21500
#define IDS_COLUMNSOURCE_STRING         21501
#define IDS_COLUMNDESTINATION_STRING    21502
#define IDS_COLUMNPROGRESS_STRING       21503
#define IDS_EMPTYOPERATIONTEXT_STRING   21504
#define IDS_EMPTYSOURCETEXT_STRING      21505
#define IDS_EMPTYDESTINATIONTEXT_STRING 21506
#define IDS_EMPTYBUFFERSIZETEXT_STRING  21507
#define IDS_EMPTYPRIORITYTEXT_STRING    21508
#define IDS_EMPTYERRORTEXT_STRING       21509
#define IDS_EMPTYPROCESSEDTEXT_STRING   21510
#define IDS_EMPTYTRANSFERTEXT_STRING    21511
#define IDS_EMPTYTIMETEXT_STRING        21512
#define IDS_CURRENTPASS_STRING          21513
#define IDS_AVERAGEWORD_STRING          21514
#define IDS_STATUSTITLE_STRING          21515
#define IDS_REPLACEPATHSTEXT_STRING     21516
#define IDS_TASKNOTPAUSED_STRING        21517
#define IDS_TASKNOTSELECTED_STRING      21518
#define IDS_NONEINPUTFILE_STRING        21519
#define IDS_COPYWORDLESSFIVE_STRING     21520
#define IDS_COPYWORDMOREFOUR_STRING     21521
#define IDS_STATUS0_STRING              21522
#define IDS_STATUS1_STRING              21523
#define IDS_STATUS2_STRING              21524
#define IDS_STATUS3_STRING              21525
#define IDS_STATUS4_STRING              21526
#define IDS_STATUS5_STRING              21527
#define IDS_STATUS6_STRING              21528
#define IDS_STATUS7_STRING              21529
#define IDS_STATUS8_STRING              21530
#define IDS_STATUS9_STRING              21531
#define IDS_STATUS10_STRING             21532
#define IDS_STATUS11_STRING             21533
#define IDS_SHELLEXECUTEERROR_STRING    21534
#define IDS_BSDEFAULT_STRING            21535
#define IDS_BSONEDISK_STRING            21536
#define IDS_BSTWODISKS_STRING           21537
#define IDS_BSCD_STRING                 21538
#define IDS_BSLAN_STRING                21539
#define IDS_EMPTYASSOCFILE_STRING       21549
#define IDS_FILTERING_STRING            21550
#define IDS_CONFIRMCANCEL_STRING        21551
#define ID_POPUP_SHOW_STATUS            32773
#define ID_POPUP_TIME_CRITICAL          32774
#define ID_POPUP_HIGHEST                32775
#define ID_POPUP_ABOVE_NORMAL           32776
#define ID_POPUP_NORMAL                 32777
#define ID_POPUP_BELOW_NORMAL           32778
#define ID_POPUP_LOWEST                 32779
#define ID_POPUP_IDLE                   32780
#define ID_POPUP_CUSTOM_BUFFERSIZE      32793
#define ID_POPUP_OPTIONS                32802
#define ID_SHOW_MINI_VIEW               32803
#define ID_POPUP_CUSTOM_COPY            32804
#define ID_POPUP_REPLACE_PATHS          32805
#define ID_POPUP_MONITORING             32806
#define ID_POPUP_SHUTAFTERFINISHED      32807
#define ID_POPUP_REGISTERDLL            32809
#define ID_POPUP_UNREGISTERDLL          32810
#define ID_POPUP_HELP                   32814
#define ID_POPUP_TEMP                   32815
#define ID_POPUP_CHECKFORUPDATES        32816
#define ID_POPUP_TOOLS                  32817

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        215
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1300
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
